# Generated by Django 5.0.4 on 2024-05-05 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.UUIDField(default=57104, editable=False),
        ),
    ]
