# Generated by Django 5.0.4 on 2024-05-05 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_student_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='parent_id',
            field=models.UUIDField(default=69731, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher_id',
            field=models.UUIDField(default=25536, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.UUIDField(default=31234, editable=False, unique=True),
        ),
    ]
