# Generated by Django 5.0.4 on 2024-05-12 13:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_attendance_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
