# Generated by Django 5.0.4 on 2024-05-12 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_grade_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='lesson_status',
            field=models.CharField(choices=[('tugagan', 'tugagan'), ('boshlangan', 'boshlangan'), ('kutilmoqda', 'kutilmoqda')], max_length=50, null=True),
        ),
    ]
